--- !ruby/object:VR_ENV
browser: firefox
width: 800
height: 600
panel_pos: 360
backup_path: C:/Users/ercjss
tab_spaces: 2
run_command_line: ruby main.rb
open_files:
- D:/Ercjss\RubymineProjects\Untitled
open_folders: []
current_file: D:/Ercjss\RubymineProjects\Untitled
glade_path: glade-3
font_name: Monospace 10
rdoc_command_line: rdoc -x README
